# Convolution

In [ ]:
import numpy as np
import scipy as sc
from scipy import signal

In [59]:
_filter = np.array([
    [0, 1, 0],
    [1, 1, 1],
    [0, 1, 0],
])

image = np.array([
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0],
])

cnv_shape = (image.shape[0] - _filter.shape[0] + 1, image.shape[1] - _filter.shape[1] + 1)
cnv = np.zeros(cnv_shape)
cnv

for i in range(cnv_shape[0]):
    for j in range(cnv_shape[1]):
        cnv[i][j] = (image[i:i+_filter.shape[0], j:j+_filter.shape[0]] * _filter).sum()

cnv

array([[5., 3., 5., 3., 5.],
       [3., 4., 3., 4., 3.],
       [5., 3., 5., 3., 5.]])

In [72]:
def get_cnv_zeros(image_shape: tuple, filter_shape: tuple) -> np.ndarray:
    cnv_shape = (image_shape[0] - filter_shape[0] + 1, image_shape[1] - filter_shape[1] + 1)
    return np.zeros(cnv_shape)

def convolve(image: np.ndarray, _filter: np.ndarray) -> np.ndarray:
    cnv = get_cnv_zeros(image.shape, _filter.shape)
    for i in range(cnv_shape[0]):
        for j in range(cnv_shape[1]):
            cnv[i][j] = (image[i:i+_filter.shape[0], j:j+_filter.shape[0]] * _filter).sum()
    return cnv

In [73]:
convolve(image, _filter)

array([[5., 3., 5., 3., 5.],
       [3., 4., 3., 4., 3.],
       [5., 3., 5., 3., 5.]])

In [74]:
get_cnv_zeros(image.shape, _filter.shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
_filter = np.array(
    [[0, 1, 0],
     [1, 1, 1],
     [0, 1, 0]
    ]
)

image = np.array([
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0]
    ])

s_x=1
s_y=1

res = signal.convolve2d(image, _filter[::-1, ::-1], mode='valid')[::s_y, ::s_x]
res

array([[5, 3, 5, 3, 5],
       [3, 4, 3, 4, 3],
       [5, 3, 5, 3, 5]])