# Convolution

In [1]:
import numpy as np
import scipy as sc
from scipy import signal

In [43]:
_filter = np.array([
    [0, 1, 0],
    [1, 1, 1],
    [0, 1, 0],
])

image = np.array([
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0],
])

cnv_shape = (image.shape[0] - _filter.shape[0] + 1, image.shape[1] - _filter.shape[1] + 1)
cnv = np.zeros(cnv_shape)
cnv

for i in range(cnv_shape[0]):
    for j in range(cnv_shape[1]):
        cnv[i][j] = (image[i:i+_filter.shape[0], j:j+_filter.shape[0]] * _filter).sum()

cnv

array([[5., 3., 5., 3., 5.],
       [3., 4., 3., 4., 3.],
       [5., 3., 5., 3., 5.]])

In [34]:
image = np.ones((5, 7))
padd = 1
padding_image = np.zeros((image.shape[0]+padd*2, image.shape[1]+padd*2))
padding_image[padd:-padd, padd:-padd] = image
padding_image

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
def get_cnv_zeros(image_shape: tuple, filter_shape: tuple) -> np.ndarray:
    cnv_shape = (image_shape[0] - filter_shape[0] + 1, image_shape[1] - filter_shape[1] + 1)
    return np.zeros(cnv_shape)


def get_padding(image: np.ndarray, padding: int=0) -> np.ndarray:
    padding_image = np.zeros((image.shape[0]+padding*2, image.shape[1]+padding*2))
    padding_image[padding:-padding, padding:-padding] = image
    return padding_image
    

def convolve(image: np.ndarray, _filter: np.ndarray, s_x: int=1, x_y: int=1, padding: int=0) -> np.ndarray:
    if padding:
        image = get_padding(image, padding)
        
    cnv = get_cnv_zeros(image.shape, _filter.shape)
    for i in range(cnv_shape[0]):
        for j in range(cnv_shape[1]):
            cnv[i][j] = (image[i:i+_filter.shape[0], j:j+_filter.shape[0]] * _filter).sum()
    return cnv



In [36]:
get_padding(np.ones((3, 8)), 3)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
convolve(image, _filter, padding=2)

array([[0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 2., 2., 3., 2., 0., 0., 0., 0.],
       [1., 2., 5., 3., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
get_cnv_zeros(image.shape, _filter.shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
_filter = np.array(
    [[0, 1, 0],
     [1, 1, 1],
     [0, 1, 0]
    ]
)

image = np.array([
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0],
    [1, 1, 1, 1, 1, 1, 1],
    [0, 1, 0, 1, 0, 1, 0]
    ])

s_x=1
s_y=1

res = signal.convolve2d(image, _filter[::-1, ::-1], mode='valid')[::s_y, ::s_x]
res

array([[5, 3, 5, 3, 5],
       [3, 4, 3, 4, 3],
       [5, 3, 5, 3, 5]])